faed_management_tool/faed_management_tool/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from faed_drone_publisher.views import drone_detail
from faed_management.views import HangarsList, DropPointsList, \
    MeteoStationsList
# MeteoStationsView, HangarsView, DropPointsView
from django.views.generic.base import TemplateView
from rest_framework import routers
from faed_management import views

from faed_management.static.py_func.sendtoLG import sync_kmls_file
from faed_management.static.py_func.sendtoLG import sync_kmls_to_galaxy


router = routers.DefaultRouter()
router.register(r'hangars', views.HangarViewSet, 'hangars')
router.register(r'droppoints', views.DropPointViewSet, 'droppoints')
router.register(r'meteostations', views.MeteoStationViewSet, 'meteostations')

urlpatterns = [
    # url(r'^$', TemplateView.as_view(template_name='index.html')),
    # url(r'^index/$', Templates_view(template_name='index.html')),

    url(r'^$', views.base, name="base"),
    url(r'^index/$', views.base, name="index"),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^api/', include(router.urls)),
    # url(r'^api-auth/',
    #     include('rest_framework.urls', namespace='rest_framework')),

    url(r'^styleurlform/$', views.submit_styleurl),

    # url(r'^hangars/$', HangarsView.as_view(), name='hangars-list'),
    url(r'^hangars/$', views.hangar_per_city, name='hangar-list'),
    url(r'^hangar_list/$', HangarsList.as_view()),
    url(r'^hangars/delete_hangar/(?P<id>\w+)/$', views.delete_hangar),
    url(r'^hangars/edit_hangar/(?P<id>\w+)/$', views.edit_hangar),
    url(r'^hangarform/$', views.submit_hangar),

    # url(r'^droppoints/$', DropPointsView.as_view(), name='droppoint-list'),
    url(r'^droppoints/$', views.droppoint_per_city, name='droppoint-list'),
    url(r'^droppoints/delete_droppoint/(?P<id>\w+)/$', views.delete_droppoint),
    url(r'^droppoints/edit_droppoint/(?P<id>\w+)/$', views.edit_droppoint),
    url(r'^droppoint_list/$', DropPointsList.as_view()),
    url(r'^droppointform/$', views.submit_droppoint),

    url(r'^cityform/$', views.submit_city),

    url(r'^altitude/(?P<latitude>\d+\.\d+)/(?P<longitude>\d+\.\d+)/$', views.get_altitude, name='latitude'),


    # url(r'^meteostations/$',
    # MeteoStationsView.as_view(), name='meteostations_list'),
    url(r'^meteostations/$', views.meteostations_per_city,
        name='meteostations_list'),
    url(r'^meteostations/delete_meteostation/(?P<id>\w+)/$',
        views.delete_meteostation),
    url(r'^meteostations/edit_meteostation/(?P<id>\w+)/$',
        views.edit_meteostation),
    url(r'^meteostations_list/$', MeteoStationsList.as_view()),
    url(r'^meteostationform/$', views.submit_meteostation),

    url(r'^droneform/$', views.submit_drone),
    url(r'^drone/(?P<drone_plate>\w+)/$', drone_detail),

    url(r'^refresh_kml/$', views.refresh_kml),
    url(r'^incidence/$', views.find_emergency_path),


]

faed_management_tool/faed_management/models.py
from django.db import models


class City(models.Model):
    name = models.CharField(max_length=100)
    lat = models.FloatField(default='0')
    lng = models.FloatField(default='0')

    def __unicode__(self):
        return str(self.name)


class StyleURL(models.Model):
    name = models.CharField(max_length=50)
    href = models.URLField()
    scale = models.FloatField()

    def __unicode__(self):
        return str(self.name)


class DropPoint(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    altitude = models.FloatField()
    is_available = models.BooleanField(default=True)
    style_url = models.ForeignKey(StyleURL)
    city = models.ForeignKey(City)

    def __unicode__(self):
        return str(self.name)


class Drone(models.Model):
    name = models.CharField(max_length=50)
    plate = models.CharField(max_length=50)
    origin_lat = models.FloatField(null=True)
    origin_lon = models.FloatField(null=True)
    destination_lat = models.FloatField(null=True)
    destination_lon = models.FloatField(null=True)
    # altitude = models.FloatField(default=50)
    emergency = models.CharField(max_length=50, null=True)
    battery_life = models.PositiveSmallIntegerField(default=100)
    style_url = models.ForeignKey(StyleURL)

    def __unicode__(self):
        return str(self.name + '-' + self.plate)


class Hangar(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    altitude = models.FloatField()
    radius = models.FloatField()
    is_available = models.BooleanField(default=True)
    style_url = models.ForeignKey(StyleURL)
    drop_points = models.ManyToManyField(DropPoint)
    drone = models.ForeignKey(Drone)
    city = models.ForeignKey(City)

    def __unicode__(self):
        return str(self.name)


class MeteoStation(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    altitude = models.FloatField()
    is_available = models.BooleanField(default=True)
    style_url = models.ForeignKey(StyleURL)

    tmp_now = models.FloatField(default=0.0)
    tmp_max = models.FloatField(default=0.0)
    tmp_min = models.FloatField(default=0.0)
    humidity = models.FloatField(default=0.0)
    precipitation = models.FloatField(default=0.0)
    pressure = models.FloatField(default=0.0)
    wind = models.FloatField(default=0.0)

    city = models.ForeignKey(City)

    def __unicode__(self):
        return str(self.name)


class Incidence(models.Model):
    lat = models.FloatField()
    long = models.FloatField()
    is_active = models.BooleanField(default=True)
    dropPoint = models.ForeignKey(DropPoint)
    hangar = models.ForeignKey(Hangar)
    drone = models.ForeignKey(Drone, null=True)

faed_management_tool/faed_management/views.py
import os
import sys
import requests
import json

from django.contrib.gis.measure import D
from django.contrib.gis.geos.point import Point
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, FileResponse
from rest_framework import viewsets
import forms
import models
from kmls_management.models import Kml
from kmls_management import kml_generator
from faed_management.static.py_func.weather import can_fly, generate_weather

from faed_management.static.py_func.sendtoLG import \
    get_server_ip, sync_kmls_file, sync_kmls_to_galaxy

from faed_management_tool.settings import MAPS_API_KEY
from serializers import HangarSerializer, DropPointSerializer, \
    MeteoStationSerializer
from faed_management.models import Hangar, DropPoint, MeteoStation, StyleURL, \
    Drone
from faed_management.forms import HangarForm, MeteoStationForm, DropPointForm,\
    StyleURLForm, DroneForm


# List items
class HangarsList(ListView):
    model = Hangar


class HangarsView(ListView):
    template_name = 'hangars.html'
    context_object_name = 'hangars'
    queryset = models.Hangar.objects.all()
    success_url = "/hangars"


def hangar_per_city(request):
    hangars = models.Hangar.objects.all()
    cities = models.City.objects.all()

    sorted_dict = {}

    for hangar in hangars:
        try:
            sorted_dict[hangar.city].append(hangar)
        except KeyError:
            sorted_dict[hangar.city] = [hangar]

    return render(request, 'hangars.html',
                  {'cities': cities, 'hangars_city': sorted_dict})


class MeteoStationsList(ListView):
    model = MeteoStation


class MeteoStationsView(ListView):
    template_name = 'meteostations.html'
    context_object_name = 'meteostations'
    queryset = models.MeteoStation.objects.all()
    success_url = "/meteostations"


def meteostations_per_city(request):
    meteostations = models.MeteoStation.objects.all()
    cities = models.City.objects.all()

    sorted_dict = {}

    for meteostation in meteostations:
        try:
            sorted_dict[meteostation.city].append(meteostation)
        except KeyError:
            sorted_dict[meteostation.city] = [meteostation]

    return render(request, 'meteostations.html',
                  {'cities': cities, 'meteostations_city': sorted_dict})


class DropPointsList(ListView):
    model = DropPoint


class DropPointsView(ListView):
    template_name = 'droppoints.html'
    context_object_name = 'droppoints'
    queryset = models.DropPoint.objects.all()
    success_url = "/droppoints"


def droppoint_per_city(request):
    droppoints = models.DropPoint.objects.all()
    cities = models.City.objects.all()

    sorted_dict = {}

    for droppoint in droppoints:
        try:
            sorted_dict[droppoint.city].append(droppoint)
        except KeyError:
            sorted_dict[droppoint.city] = [droppoint]

    return render(request, 'droppoints.html', {'cities': cities,
                                               'droppoints_city': sorted_dict})


# Forms

def submit_city(request):
    if request.method == 'POST':
        form = forms.CityForm(request.POST)

        if form.is_valid():
            city = form.save(commit=False)
            city.save()

            return HttpResponseRedirect('/')
    else:
        form = forms.CityForm()

    return render(request, 'city_form.html', {'form': form})


def submit_styleurl(request):
    if request.method == 'POST':
        form = forms.StyleURLForm(request.POST)

        if form.is_valid():
            styleurl = form.save(commit=False)
            styleurl.save()

            return HttpResponseRedirect('/')
    else:
        form = forms.StyleURLForm()

    return render(request, 'styleurl_form.html', {'form': form})


@csrf_exempt
def submit_droppoint(request):
    if request.method == 'POST':
        form = forms.DropPointForm(request.POST)

        if form.is_valid():
            droppoint = form.save(commit=False)
            droppoint.save()
            create_kml(droppoint, "droppoint", "create")
            # sync_kmls_file()
            # sync_kmls_to_galaxy()

            return HttpResponseRedirect('/droppoints/')
    else:
        form = forms.DropPointForm()

    return render(request, 'droppoint_form.html', {'form': form})


def submit_drone(request):
    if request.method == 'POST':
        form = forms.DroneForm(request.POST)

        if form.is_valid():
            drone = form.save(commit=False)
            drone.save()
            return HttpResponseRedirect('/hangars/')
    else:
        form = forms.DroneForm()

        return render(request, 'drone_form.html', {'form': form})


def submit_hangar(request):
    if request.method == 'POST':
        form = forms.HangarForm(request.POST)

        if form.is_valid():
            hangar = form.save(commit=False)
            hangar.drone.origin_lat = hangar.latitude
            hangar.drone.origin_lon = hangar.longitude
            # drone.altitude = altitude
            hangar.drone.save()
            hangar.save()
            create_kml(hangar, "hangar", "create")
            # sync_kmls_file()
            # sync_kmls_to_galaxy()

            return HttpResponseRedirect('/hangars/')
    else:
        form = forms.HangarForm()

    return render(request, 'hangar_form.html', {'form': form})


def submit_meteostation(request):
    if request.method == 'POST':
        form = forms.MeteoStationForm(request.POST)
        if form.is_valid():
            meteostation = form.save(commit=False)
            meteostation.save()
            create_kml(meteostation, "meteo", "create")
            # sync_kmls_file()
            # sync_kmls_to_galaxy()
            return HttpResponseRedirect('/meteostations/')
    else:

        form = forms.MeteoStationForm()
    return render(request, 'meteostation_form.html', {'form': form})


# REST API
class HangarViewSet(viewsets.ModelViewSet):
    queryset = models.Hangar.objects.all()
    serializer_class = HangarSerializer


class DropPointViewSet(viewsets.ModelViewSet):
    queryset = models.DropPoint.objects.all()
    serializer_class = DropPointSerializer


class MeteoStationViewSet(viewsets.ModelViewSet):
    queryset = models.MeteoStation.objects.all()
    serializer_class = MeteoStationSerializer


# Delte items
def delete_hangar(request, id):
    hangar = Hangar.objects.get(pk=id)
    delete_kml(hangar.id, "hangar")
    hangar.delete()
    return HttpResponseRedirect('/hangars/')


def delete_droppoint(request, id):
    droppoint = DropPoint.objects.get(pk=id)
    delete_kml(droppoint.id, "droppoint")
    droppoint.delete()
    return HttpResponseRedirect('/droppoints/')


def delete_meteostation(request, id):
    meteostation = MeteoStation.objects.get(pk=id)
    delete_kml(meteostation.id, "meteo")
    meteostation.delete()
    return HttpResponseRedirect('/meteostations/')


# Edit items
def edit_styleurl(request, id):
    requested_styleurl = StyleURL.objects.get(pk=id)
    form = StyleURLForm(instance=requested_styleurl)
    if request.method == 'POST':
        form = StyleURLForm(request.POST, instance=requested_styleurl)
        if form.is_valid():
            styleurl = form.save(commit=False)
            styleurl.save()

            return HttpResponseRedirect('/')

    return render(request, 'styleurl_form.html', {'form': form})


def edit_drone(request, id):
    requested_drone = Drone.objects.get(pk=id)
    form = DroneForm(instance=requested_drone)
    if request.method == 'POST':
        form = DroneForm(request.POST, instance=requested_drone)
        if form.is_valid():
            drone = form.save(commit=False)
            drone.save()

            return HttpResponseRedirect('/hangars')

    return render(request, 'drone_form.html', {'form': form})


def edit_hangar(request, id):
    requested_hangar = Hangar.objects.get(pk=id)
    form = HangarForm(instance=requested_hangar)
    if request.method == 'POST':
        form = HangarForm(request.POST, instance=requested_hangar)
        if form.is_valid():
            hangar = form.save(commit=False)
            hangar.drone.origin_lat = hangar.latitude
            hangar.drone.origin_lon = hangar.longitude
            # drone.altitude = altitude
            hangar.drone.save()
            hangar.save()
            create_kml(hangar, "hangar", "edit")

            # sync_kmls_file()
            # sync_kmls_to_galaxy()

            return HttpResponseRedirect('/hangars')

    return render(request, 'hangar_form.html', {'form': form})


def edit_meteostation(request, id):
    requested_meteo = MeteoStation.objects.get(pk=id)
    form = MeteoStationForm(instance=requested_meteo)
    if request.method == 'POST':
        form = MeteoStationForm(request.POST, instance=requested_meteo)
        if form.is_valid():
            meteostation = form.save(commit=False)
            meteostation.save()
            create_kml(meteostation, "meteo", "edit")
            # sync_kmls_file()
            # sync_kmls_to_galaxy()
            return HttpResponseRedirect('/meteostations')

    return render(request, 'meteostation_form.html', {'form': form})


def edit_droppoint(request, id):
    requested_droppoint = DropPoint.objects.get(pk=id)
    form = DropPointForm(instance=requested_droppoint)
    if request.method == 'POST':
        form = DropPointForm(request.POST, instance=requested_droppoint)
        if form.is_valid():
            droppoint = form.save(commit=False)
            droppoint.save()
            create_kml(droppoint, "droppoint", "edit")
            # sync_kmls_file()
            # sync_kmls_to_galaxy()

            return HttpResponseRedirect('/droppoints')

    return render(request, 'droppoint_form.html', {'form': form})


# Support functions
def create_kml(item, type, action):
    name = type + "_" + str(item.id) + ".kml"

faed_management_tool/faed_management/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">

    <!--Import materialize.css -->
    <link type="text/css" rel="stylesheet" href="/static/css/materialize.min.css" media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="/static/css/style.css" media="screen,projection"/>

    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="/static/js/materialize.min.js"></script>
    <script type="text/javascript" src="/static/js/drones.js"></script>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <title>FAED</title>

    <script src="https://maps.googleapis.com/maps/api/js?key={{ maps_key }}"></script>

    <script>
        // This example creates circles on the map, representing
        // radiuss in North America.

        var map;
        var image1 = {
            url: '/static/img/faeddrone100x100.png',
            // This marker is 20 pixels wide by 32 pixels tall.
            size: new google.maps.Size(100, 100),
            // The origin for this image is 0,0.
            origin: new google.maps.Point(0,0),
            // The anchor for this image is the base of the flagpole at 0,32.
            anchor: new google.maps.Point(50, 50)
        };

        var image2 = {
            url: '/static/img/marker.png',


        };
        var markers = [];
        var circles = [];


        var hangars = {};
        var droppoints = [];

        hangars = loadHangars();
        droppoints = loadDroppoints();


        var cityCircle;


        function initialize() {


            // Create the map.
            var mapOptions = {
                zoom: 13,
                center: new google.maps.LatLng(41.617147, 0.624870),
                mapTypeId: google.maps.MapTypeId.HYBRID
            };

            map = new google.maps.Map(document.getElementById('map-canvas'),
                    mapOptions);

            // Construct the circle for each value in hangar.
            // Note: We scale the area of the circle based on the radius.
            for (var city in hangars) {
                if (hangars[city].availability){
                    addMarkerIcon(hangars[city].center, map, image1, hangars[city].title);
                    addCircle(hangars[city].center, map, hangars[city].title, hangars[city].radius);
                }
            }


            for (var point in droppoints) {
                if(droppoints[point].availability){
                    addMarker(droppoints[point].center, map , droppoints[point].title,droppoints[point].name, droppoints[point].description);
                }

            }

            map.addListener('click', function(e) {
                placeMarkerAndPanTo(e.latLng, map);
            });

        }

        google.maps.event.addDomListener(window, 'load', initialize);

        var infowindow = new google.maps.InfoWindow({
        });

        var marker = new google.maps.Marker({
            icon: 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png'
        });

        marker.addListener('click', function() {
            infowindow.open(map, marker);
        });

        function placeMarkerAndPanTo(latLng, map) {
            marker.setPosition(latLng)
            marker.setMap(map)
            map.panTo(latLng);
            infowindow.setContent("<a onclick=\"show_incidence(\'" + "{{ url_base }}" + "incidence/?lat=" + latLng.lat() + "&lng=" + latLng.lng() + "\')\" style=\"cursor: pointer;\">Create Emergency</a>");
            infowindow.open(map, marker);
        }

    </script>

    <script>
        $(document).ready(function(){
            // Initialize collapse button
            $(".button-collapse").sideNav();
            // Initialize collapsible (uncomment the line below if you use the dropdown variation)
            //$('.collapsible').collapsible();

            $('.meteostations').on('click', function(){
                testingjquery();
            })

            $('.droppoint').on('click', function(){

                var $el = $(this);
                var isSelected = $el.attr('data-selected');

                if( isSelected != 'true' ){
                    for(var i=0;i<markers.length;i++){
                        if(markers[i].title =="droppoint"){
                            markers[i].setVisible(false);
                        }
                    }
                    $el.attr('data-selected', true)
                }else{
                    for(var i=0;i<markers.length;i++){
                        if(markers[i].title =="droppoint"){
                            markers[i].setVisible(true);
                        }
                    }            $el.attr('data-selected', false)
                }

            })


            $('.hangar').on('click', function(){
                var $el = $(this);
                var isSelected = $el.attr('data-selected');

                if( isSelected != 'true' ){
                    for(var i=0;i<markers.length;i++){
                        if(markers[i].title =="hangar"){
                            markers[i].setVisible(false);
                        }
                    }
                    for(var i=0;i<circles.length;i++){
                        if(circles[i].title =="hangar"){
                            circles[i].setVisible(false);
                        }
                    }

                    $el.attr('data-selected', true)
                }else{
                    for(var i=0;i<markers.length;i++){
                        if(markers[i].title =="hangar"){
                            markers[i].setVisible(true);
                        }
                    }
                    for(var i=0;i<circles.length;i++){
                        if(circles[i].title =="hangar"){
                            circles[i].setVisible(true);
                        }
                    }

                    $el.attr('data-selected', false)
                }

            })

        });

        function refresh_kml(){
            url_to = "/refresh_kml";
            $.ajax({url: url_to});
        }

        function show_incidence(url){
            $.ajax({url: url});
        }



    </script>
</head>

<body>

<div id="menu-top">
    <nav style="position: fixed;">
        <ul id="slide-out" class="side-nav">
            <p class="center-align">
                <img src="/static/img/faed_logo.png" width="200px"/>
            </p>
            <li><a href="/index">
                <i class="material-icons small" style="margin: 10px; position:relative; top:7px;">map</i>Map</a>
            </li>
            <li><a href="/hangars">
                <i class="material-icons small" style="margin: 10px; position:relative; top:7px;">open_with</i>Hangars</a>
            </li>
            <li><a href="/droppoints">
                <i class="material-icons small" style="margin: 10px; position:relative; top:7px;">pin_drop</i>DropPoints</a>
            </li>
            <li><a href="/meteostations">
                <i class="material-icons small" style="margin: 10px; position:relative; top:7px;">satellite</i>Stations</a>
            </li>
            <li><a onclick="refresh_kml('{{ url }}')">
                <i class="material-icons small" style="margin: 10px; position:relative; top:7px;">autorenew</i>Refresh KML</a>
            </li>
        </ul>
        <a href="#" style="cursor: pointer"  data-activates="slide-out" class="button-collapse  show-on-large"><i class="mdi-navigation-menu"></i></a>
    </nav>
</div>

{% block content %}
{% endblock content %}
</body>
<footer class="page-footer" style="position: fixed;">
    <div class="footer-copyright">
        <div class="container">
            © 2015 Open Source
            <a class="grey-text text-lighten-4 right" href="http://www.faeddroneproject.com/">FAED Project</a>
        </div>
    </div>
</footer>
</html>

faed_management_tool/faed_management/templates/city_form.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <form class="col s12" method="post" enctype="multipart/form-data" action="">
                {% csrf_token %}
                {{ form.non_field_errors }}
                {{ form.as_p }}


                    <button class="waves-effect waves-light btn-large green" name="action" type="submit">
                        <i class="material-icons right">send</i>SAVE
                    </button>

            </form>
        </div>
    </div>
{% endblock content %}

faed_management_tool/faed_management/templates/drone_form.html
{% extends "base.html" %}

{% block content %}

    <div class="container" style="margin-top:3%">
        <div class="row">
            <form class="col s12" method="post" enctype="multipart/form-data" action="">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="row">
                    <div class="input-field col l6 s12 ">
                        {{ form.name.error }}
                        <label for="name" data-error="wrong" data-success="right">Nom</label>
                        {{ form.name }}
                    </div>
                    <div class="input-field col l6 s12">
                        <label for="plate">License Plate</label>
                        {{ form.plate }}
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        {{ form.style_url }}
                        <a class="material-icons" href="/styleurlform" target="_blank">add</a>
                    </div>
                    <button class="waves-effect waves-light btn-large" name="action" type="submit">
                        <i class="material-icons right">send</i>Guardar
                    </button>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}

faed_management_tool/faed_management/templates/droppoint_form.html
{% extends "base.html" %}

{% block content %}

    <div class="container" style="margin-top:3%;">
        <div class="row">
            <form class="col s12" method="post" enctype="multipart/form-data" action="">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="row">
                    <div class="input-field col l8">
                        {{ form.name.error }}
                        <label for="name" data-error="wrong" data-success="right">Nom</label>
                        {{ form.name }}
                    </div>
                    <div class="input-field col l4">
                        {% if form.is_available.value %}
                            <input id="is_available" name="is_available" type="checkbox" class="validate teal-text text-darken-3" checked="checked">
                        {% else  %}
                            <input id="is_available" name="is_available" type="checkbox" class="validate teal-text text-darken-3">
                        {% endif %}
                        <label for="is_available">Availability</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col l4 m4 s12">
                        <label for="latitude">Latitude</label>
                        {{ form.latitude }}
                    </div>
                    <div class="input-field col l4 m4 s12">
                        {{ form.longitude }}
                        <label for="longitude">Longitude</label>
                    </div>
                    <div class="input-field col l4 m4 s12">
                        {{ form.altitude}}
                        <label for="altitude">Altitude</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col l6 s12">
                        {{ form.style_url }}
                        <a class="material-icons" href="/styleurlform" target="_blank">add</a>
                    </div>
                    <div class="input-field col l6 s12">
                        {{ form.city }}
                        <a class="material-icons" href="/cityform" target="_blank">add</a>
                    </div>
                </div>

                                <div id="map-canvas" style="height:300px; margin-bottom:5%;"></div>


                <div class="row">
                    <div class="input-field col s6">
                        <label for="description">Description</label>
                        {{ form.description }}
                    </div>
                    <button class="waves-effect waves-light btn-large green" name="action" type="submit">
                        <i class="material-icons right">send</i>Save
                    </button>
                    <a href="/droppoints" class="waves-effect waves-light btn-large red">
                        <i class="material-icons right">cancel</i>Cancel</a>
                </div>

                {% include "mapsForm.html" %}


            </form>
        </div>
    </div>

{% endblock content %}

faed_management_tool/faed_management/templates/mapsForm.html
<!-- Change the id of latitude and longitude variables to display the saved marker in the map  -->

<script>
    var origin_lat = $('input#id_latitude').val();
    var origin_lng = $('input#id_longitude').val();
</script>


    <script>
// In the following example, markers appear when the user clicks on the map.
// The markers are stored in an array.
// The user can then click an option to hide, show or delete the markers.
var map;
var markers = [];



var myLatlng = new google.maps.LatLng(origin_lat,origin_lng);


function initialize() {
  var catalunya = new google.maps.LatLng(41.79537618555664, 1.2641143798828125);
  var mapOptions = {
    zoom: 8,
    center: catalunya,
    mapTypeId: google.maps.MapTypeId.HYBRID
  };

  map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
addMarker(myLatlng);
  // This event listener will call addMarker() when the map is clicked.
  google.maps.event.addListener(map, 'click', function(event) {
    setAllMap(null);

    addMarker(event.latLng);
    var lat = event.latLng.lat();
    var lng = event.latLng.lng();
    $('input#id_latitude').val(lat);
    $('input#id_longitude').val(lng);

    // retrieve altitude
    getAltitude(lat, lng, function(altitude) {
      $('input#id_altitude').val(altitude);
    });

  });


}

// Add a marker to the map and push to the array.
function addMarker(location) {
  var marker = new google.maps.Marker({
    position: location,
    map: map
  });
  markers.push(marker);
}

// Sets the map on all markers in the array.
function setAllMap(map) {
  for (var i = 0; i < markers.length; i++) {
    markers[i].setMap(map);
  }
}

// Removes the markers from the map, but keeps them in the array.
function clearMarkers() {
  setAllMap(null);
}

// Shows any markers currently in the array.
function showMarkers() {
  setAllMap(map);
}

// Deletes all markers in the array by removing references to them.
function deleteMarkers() {
  clearMarkers();
  markers = [];
}

// Returns altitude / elevation of given a current latitude and longitude
function getAltitude(lat, long, callback) {
  var url = '/altitude/' + lat + '/' + long + '/';
  $.get(url, (altitude) => callback(altitude));
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>